DROP TABLE IF EXISTS migrations;

CREATE TABLE migrations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    version VARCHAR(255) NOT NULL,
    class VARCHAR(255) NOT NULL,
    `group` VARCHAR(255) NOT NULL,
    namespace VARCHAR(255) NOT NULL,
    time INT NOT NULL,
    batch INT UNSIGNED NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
